=== SOPORTETELEMEDICINA/tlm-medicos/raml/src/schema/sla-schema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/root.json",
  "type": "object",
  "required": [
    "id_sla",
    "descripcion",
    "idCategory",
    "idSubcategory",
    "idTipoTicket",
    "horarioNatural",
    "porcentajeAlerta",
    "prioridad"
  ],
  "properties": {
    "id_sla": {
      "$id": "#/properties/id_sla",
      "type": "integer",
      "examples": [
        1
      ],
      "minimum": 1
    },
    "descripcion": {
      "$id": "#/properties/descripcion",
      "type": "string",
      "examples": [
        "gold"
      ],
      "pattern": "^(.*)$"
    },
    "idCategory": {
      "$id": "#/properties/idCategory",
      "type": "string",
      "examples": [
        ""
      ],
      "pattern": "^(.*)$"
    },
    "idSubcategory": {
      "$id": "#/properties/idSubcategory",
      "type": "string",
      "examples": [
        ""
      ],
      "pattern": "^(.*)$"
    },
    "idTipoTicket": {
      "$id": "#/properties/idTipoTicket",
      "type": "string",
      "examples": [
        ""
      ],
      "pattern": "^(.*)$"
    },
    "horarioNatural": {
      "$id": "#/properties/horarioNatural",
      "type": "boolean",
      "examples": [
        false
      ]
    },
    "porcentajeAlerta": {
      "$id": "#/properties/porcentajeAlerta",
      "type": "integer",
      "examples": [
        90
      ],
      "minimum": 0.0,
      "maximum": 100.0
    },
    "prioridad": {
      "$id": "#/properties/prioridad",
      "type": "array",
      "items": [
        {
          "$id": "#/properties/prioridad/items/0",
          "type": "object",
          "required": [
            "idSladetail",
            "prioridad",
            "tiempioRespuesta",
            "tiempoResolucion",
            "idSla",
            "escalacion1_resp",
            "escalacion2_resp",
            "escalacion3_resp",
            "escalacion4_resp"
          ],
          "properties": {
            "idSladetail": {
              "$id": "#/properties/prioridad/items/0/properties/idSladetail",
              "type": "integer",
              "examples": [
                6
              ],
              "minimum": 1
            },
            "prioridad": {
              "$id": "#/properties/prioridad/items/0/properties/prioridad",
              "type": "integer",
              "examples": [
                1
              ],
              "minimum": 1
            },
            "tiempioRespuesta": {
              "$id": "#/properties/prioridad/items/0/properties/tiempioRespuesta",
              "type": "integer",
              "examples": [
                60
              ],
              "minimum": 1
            },
            "tiempoResolucion": {
              "$id": "#/properties/prioridad/items/0/properties/tiempoResolucion",
              "type": "integer",
              "examples": [
                240
              ],
              "minimum": 1
            },
            "idSla": {
              "$id": "#/properties/prioridad/items/0/properties/idSla",
              "type": "integer",
              "examples": [
                1
              ],
              "minimum": 1
            },
            "escalacion1_resp": {
              "$id": "#/properties/prioridad/items/0/properties/escalacion1_resp",
              "type": "string",
              "examples": [
                "Juan@gmail.com, Ernesto@gmail.com"
              ],
              "pattern": "^(.*)$"
            },
            "escalacion2_resp": {
              "$id": "#/properties/prioridad/items/0/properties/escalacion2_resp",
              "type": "string",
              "examples": [
                "Luis@gmail.com, p@p.com, j@j.com"
              ],
              "pattern": "^(.*)$"
            },
            "escalacion3_resp": {
              "$id": "#/properties/prioridad/items/0/properties/escalacion3_resp",
              "type": "string",
              "examples": [
                "Antonio@gmail.com"
              ],
              "pattern": "^(.*)$"
            },
            "escalacion4_resp": {
              "$id": "#/properties/prioridad/items/0/properties/escalacion4_resp",
              "type": "string",
              "examples": [
                "David@gmail.com"
              ],
              "pattern": "^(.*)$"
            }
          }
        },
        {
          "$id": "#/properties/prioridad/items/1",
          "type": "object",
          "required": [
            "idSladetail",
            "prioridad",
            "tiempioRespuesta",
            "tiempoResolucion",
            "slaId",
            "escalacion1_resp",
            "escalacion2_resp",
            "escalacion3_resp",
            "escalacion4_resp"
          ],
          "properties": {
            "idSladetail": {
              "$id": "#/properties/prioridad/items/1/properties/idSladetail",
              "type": "integer",
              "examples": [
                7
              ],
              "minimum": 1
            },
            "prioridad": {
              "$id": "#/properties/prioridad/items/1/properties/prioridad",
              "type": "integer",
              "examples": [
                2
              ],
              "minimum": 1
            },
            "tiempioRespuesta": {
              "$id": "#/properties/prioridad/items/1/properties/tiempioRespuesta",
              "type": "integer",
              "examples": [
                120
              ],
              "minimum": 1
            },
            "tiempoResolucion": {
              "$id": "#/properties/prioridad/items/1/properties/tiempoResolucion",
              "type": "integer",
              "examples": [
                480
              ],
              "minimum": 1
            },
            "slaId": {
              "$id": "#/properties/prioridad/items/1/properties/slaId",
              "type": "integer",
              "examples": [
                1
              ],
              "minimum": 1
            },
            "escalacion1_resp": {
              "$id": "#/properties/prioridad/items/1/properties/escalacion1_resp",
              "type": "string",
              "examples": [
                "Juan@gmail.com, Ernesto@gmail.com"
              ],
              "pattern": "^(.*)$"
            },
            "escalacion2_resp": {
              "$id": "#/properties/prioridad/items/1/properties/escalacion2_resp",
              "type": "string",
              "examples": [
                "Luis@gmail.com, p@p.com, j@j.com"
              ],
              "pattern": "^(.*)$"
            },
            "escalacion3_resp": {
              "$id": "#/properties/prioridad/items/1/properties/escalacion3_resp",
              "type": "string",
              "examples": [
                "Antonio@gmail.com"
              ],
              "pattern": "^(.*)$"
            },
            "escalacion4_resp": {
              "$id": "#/properties/prioridad/items/1/properties/escalacion4_resp",
              "type": "string",
              "examples": [
                "David@gmail.com"
              ],
              "pattern": "^(.*)$"
            }
          }
        },
        {
          "$id": "#/properties/prioridad/items/2",
          "type": "object",
          "required": [
            "idSladetail",
            "prioridad",
            "tiempioRespuesta",
            "tiempoResolucion",
            "slaId",
            "escalacion1_resp",
            "escalacion2_resp",
            "escalacion3_resp",
            "escalacion4_resp"
          ],
          "properties": {
            "idSladetail": {
              "$id": "#/properties/prioridad/items/2/properties/idSladetail",
              "type": "integer",
              "examples": [
                8
              ],
              "minimum": 1
            },
            "prioridad": {
              "$id": "#/properties/prioridad/items/2/properties/prioridad",
              "type": "integer",
              "examples": [
                3
              ],
              "minimum": 1
            },
            "tiempioRespuesta": {
              "$id": "#/properties/prioridad/items/2/properties/tiempioRespuesta",
              "type": "integer",
              "examples": [
                240
              ],
              "minimum": 1
            },
            "tiempoResolucion": {
              "$id": "#/properties/prioridad/items/2/properties/tiempoResolucion",
              "type": "integer",
              "examples": [
                960
              ],
              "minimum": 1
            },
            "slaId": {
              "$id": "#/properties/prioridad/items/2/properties/slaId",
              "type": "integer",
              "examples": [
                1
              ],
              "minimum": 1
            },
            "escalacion1_resp": {
              "$id": "#/properties/prioridad/items/2/properties/escalacion1_resp",
              "type": "string",
              "examples": [
                "Juan@gmail.com, Ernesto@gmail.com"
              ],
              "pattern": "^(.*)$"
            },
            "escalacion2_resp": {
              "$id": "#/properties/prioridad/items/2/properties/escalacion2_resp",
              "type": "string",
              "examples": [
                "Luis@gmail.com, p@p.com, j@j.com"
              ],
              "pattern": "^(.*)$"
            },
            "escalacion3_resp": {
              "$id": "#/properties/prioridad/items/2/properties/escalacion3_resp",
              "type": "string",
              "examples": [
                "Antonio@gmail.com"
              ],
              "pattern": "^(.*)$"
            },
            "escalacion4_resp": {
              "$id": "#/properties/prioridad/items/2/properties/escalacion4_resp",
              "type": "string",
              "examples": [
                "David@gmail.com"
              ],
              "pattern": "^(.*)$"
            }
          }
        },
        {
          "$id": "#/properties/prioridad/items/3",
          "type": "object",
          "required": [
            "idSladetail",
            "prioridad",
            "tiempioRespuesta",
            "tiempoResolucion",
            "slaId",
            "escalacion1_resp",
            "escalacion2_resp",
            "escalacion3_resp",
            "escalacion4_resp"
          ],
          "properties": {
            "idSladetail": {
              "$id": "#/properties/prioridad/items/3/properties/idSladetail",
              "type": "integer",
              "examples": [
                9
              ],
              "minimum": 1
            },
            "prioridad": {
              "$id": "#/properties/prioridad/items/3/properties/prioridad",
              "type": "integer",
              "examples": [
                4
              ],
              "minimum": 1
            },
            "tiempioRespuesta": {
              "$id": "#/properties/prioridad/items/3/properties/tiempioRespuesta",
              "type": "integer",
              "examples": [
                1440
              ],
              "minimum": 1
            },
            "tiempoResolucion": {
              "$id": "#/properties/prioridad/items/3/properties/tiempoResolucion",
              "type": "integer",
              "examples": [
                1920
              ],
              "minimum": 1
            },
            "slaId": {
              "$id": "#/properties/prioridad/items/3/properties/slaId",
              "type": "integer",
              "examples": [
                1
              ],
              "minimum": 1
            },
            "escalacion1_resp": {
              "$id": "#/properties/prioridad/items/3/properties/escalacion1_resp",
              "type": "string",
              "examples": [
                "Juan@gmail.com, Ernesto@gmail.com"
              ],
              "pattern": "^(.*)$"
            },
            "escalacion2_resp": {
              "$id": "#/properties/prioridad/items/3/properties/escalacion2_resp",
              "type": "string",
              "examples": [
                "Luis@gmail.com, p@p.com, j@j.com"
              ],
              "pattern": "^(.*)$"
            },
            "escalacion3_resp": {
              "$id": "#/properties/prioridad/items/3/properties/escalacion3_resp",
              "type": "string",
              "examples": [
                "Antonio@gmail.com"
              ],
              "pattern": "^(.*)$"
            },
            "escalacion4_resp": {
              "$id": "#/properties/prioridad/items/3/properties/escalacion4_resp",
              "type": "string",
              "examples": [
                "David@gmail.com"
              ],
              "pattern": "^(.*)$"
            }
          }
        }
      ]
    }
  }
}

=== SOPORTETELEMEDICINA/tlm-medicos/raml/src/json/sla.json
{
    "id_sla":1,
    "descripcion":"gold",
    "idCategory":"",
    "idSubcategory":"",
    "idTipoTicket":"",
    "horarioNatural":false,
    "porcentajeAlerta":90,
    "prioridad":[
        {
            "idSladetail":6,
            "prioridad":1,
            "tiempioRespuesta":60,
            "tiempoResolucion":240,
            "idSla":1,
            "escalacion1_resp":"Juan@gmail.com, Ernesto@gmail.com",
            "escalacion2_resp":"Luis@gmail.com, p@p.com, j@j.com",
            "escalacion3_resp":"Antonio@gmail.com",
            "escalacion4_resp":"David@gmail.com"
        },
        {
            "idSladetail":7,
            "prioridad":2,
            "tiempioRespuesta":120,
            "tiempoResolucion":480,
            "slaId":1,
            "escalacion1_resp":"Juan@gmail.com, Ernesto@gmail.com",
            "escalacion2_resp":"Luis@gmail.com, p@p.com, j@j.com",
            "escalacion3_resp":"Antonio@gmail.com",
            "escalacion4_resp":"David@gmail.com"
        },
        {
            "idSladetail":8,
            "prioridad":3,
            "tiempioRespuesta":240,
            "tiempoResolucion":960,
            "slaId":1,
            "escalacion1_resp":"Juan@gmail.com, Ernesto@gmail.com",
            "escalacion2_resp":"Luis@gmail.com, p@p.com, j@j.com",
            "escalacion3_resp":"Antonio@gmail.com",
            "escalacion4_resp":"David@gmail.com"
        },
        {
            "idSladetail":9,
            "prioridad":4,
            "tiempioRespuesta":1440,
            "tiempoResolucion":1920,
            "slaId":1,
            "escalacion1_resp":"Juan@gmail.com, Ernesto@gmail.com",
            "escalacion2_resp":"Luis@gmail.com, p@p.com, j@j.com",
            "escalacion3_resp":"Antonio@gmail.com",
            "escalacion4_resp":"David@gmail.com"
        }
    ]
}
